use crate::config::Config;
use crate::model::{KernelFile, NativeFile};

pub(crate) fn generate_api(
    config: &Config,
    files: &[KernelFile],
    native_files: &[NativeFile],
) -> String {
    let mut s = String::new();
    s.push_str("// @generated by lmrs-cudit - do not edit.\n");
    s.push_str(
        "#[allow(dead_code, unused_imports, non_snake_case, clippy::too_many_arguments)]\n\n",
    );
    s.push_str("use std::sync::Arc;\n");
    s.push_str(&format!("use {}::driver::{{sys, CudaContext, CudaFunction, CudaGraph, CudaSlice, CudaStream, DevicePtr, DevicePtrMut, DeviceRepr, DriverError, LaunchConfig, PushKernelArg, ValidAsZeroBits}};\n", config.cudarc_crate_path));
    s.push_str(&format!(
        "use {}::nvrtc::Ptx;\n\n",
        config.cudarc_crate_path
    ));

    push_tensor(&mut s);
    push_native_externs(&mut s, native_files);
    push_runtime_header(&mut s, files);
    push_runtime_methods(&mut s, files, native_files);
    push_kernel_names(&mut s, files, native_files);
    s
}

fn push_native_externs(s: &mut String, native_files: &[NativeFile]) {
    if native_files.iter().all(|file| file.functions.is_empty()) {
        return;
    }
    s.push_str("unsafe extern \"C\" {\n");
    for file in native_files {
        for function in &file.functions {
            s.push_str(&format!("    fn {}(", function.name));
            for (idx, p) in function.params.iter().enumerate() {
                if idx > 0 {
                    s.push_str(", ");
                }
                if p.is_ptr {
                    if p.is_const {
                        s.push_str(&format!("{}: *const {}", p.name, p.base_ty));
                    } else {
                        s.push_str(&format!("{}: *mut {}", p.name, p.base_ty));
                    }
                } else {
                    s.push_str(&format!("{}: {}", p.name, p.rust_ty));
                }
            }
            s.push_str(") -> i32;\n");
        }
    }
    s.push_str("}\n\n");
}

fn push_tensor(s: &mut String) {
    s.push_str("/// Device-resident tensor storage owned by a generated `Runtime`.\n");
    s.push_str("pub struct Tensor<T> {\n");
    s.push_str("    buf: CudaSlice<T>,\n");
    s.push_str("}\n\n");

    s.push_str("impl<T> Tensor<T> {\n");
    s.push_str("    /// Returns the number of elements in the tensor.\n");
    s.push_str("    pub fn len(&self) -> usize {\n");
    s.push_str("        self.buf.len()\n");
    s.push_str("    }\n\n");
    s.push_str("    /// Returns true when the tensor contains no elements.\n");
    s.push_str("    pub fn is_empty(&self) -> bool {\n");
    s.push_str("        self.len() == 0\n");
    s.push_str("    }\n\n");
    s.push_str("    /// Exposes the underlying `cudarc` slice for interop.\n");
    s.push_str("    pub fn as_cuda_slice(&self) -> &CudaSlice<T> {\n");
    s.push_str("        &self.buf\n");
    s.push_str("    }\n\n");
    s.push_str("    /// Exposes the underlying mutable `cudarc` slice for interop.\n");
    s.push_str("    pub fn as_cuda_slice_mut(&mut self) -> &mut CudaSlice<T> {\n");
    s.push_str("        &mut self.buf\n");
    s.push_str("    }\n");
    s.push_str("}\n\n");
}

fn push_runtime_header(s: &mut String, files: &[KernelFile]) {
    s.push_str("/// CUDA runtime, stream, loaded modules, and generated kernel entry points.\n");
    s.push_str("pub struct Runtime {\n");
    s.push_str("    _ctx: Arc<CudaContext>,\n");
    s.push_str("    stream: Arc<CudaStream>,\n");
    for f in files {
        for k in &f.kernels {
            s.push_str(&format!("    func_{}: CudaFunction,\n", k.name));
        }
    }
    s.push_str("}\n\n");

    s.push_str("impl Runtime {\n");
    s.push_str("    /// Creates a runtime for a CUDA device ordinal.\n");
    s.push_str("    pub fn new(ordinal: usize) -> Result<Self, DriverError> {\n");
    s.push_str("        let ctx = CudaContext::new(ordinal)?;\n");
    s.push_str("        unsafe { ctx.disable_event_tracking() };\n");
    s.push_str("        let stream = ctx.new_stream()?;\n\n");
    for f in files {
        if f.kernels.is_empty() {
            continue;
        }
        s.push_str(&format!(
            "        let module_{m} = ctx.load_module(Ptx::from_src(include_str!(concat!(env!(\"OUT_DIR\"), \"/{ptx}\"))))?;\n",
            m = f.stem,
            ptx = f.ptx_name
        ));
        for k in &f.kernels {
            s.push_str(&format!(
                "        let func_{name} = module_{m}.load_function(\"{name}\")?;\n",
                name = k.name,
                m = f.stem
            ));
        }
        s.push('\n');
    }
    s.push_str("        Ok(Self {\n");
    s.push_str("            _ctx: ctx,\n");
    s.push_str("            stream,\n");
    for f in files {
        for k in &f.kernels {
            s.push_str(&format!("            func_{},\n", k.name));
        }
    }
    s.push_str("        })\n");
    s.push_str("    }\n\n");
}

fn push_runtime_methods(s: &mut String, files: &[KernelFile], native_files: &[NativeFile]) {
    s.push_str("    /// Creates a runtime for CUDA device 0.\n");
    s.push_str("    pub fn default() -> Result<Self, DriverError> {\n");
    s.push_str("        Self::new(0)\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Returns the runtime stream.\n");
    s.push_str("    pub fn stream(&self) -> &Arc<CudaStream> {\n");
    s.push_str("        &self.stream\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Synchronizes the runtime stream.\n");
    s.push_str("    pub fn synchronize(&self) -> Result<(), DriverError> {\n");
    s.push_str("        self.stream.synchronize()\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Uploads host data into a new device-resident tensor.\n");
    s.push_str(
        "    pub fn upload<T: DeviceRepr>(&self, src: &[T]) -> Result<Tensor<T>, DriverError> {\n",
    );
    s.push_str("        Ok(Tensor { buf: self.stream.clone_htod(src)? })\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Allocates a zero-filled device-resident tensor.\n");
    s.push_str("    pub fn zeros<T: DeviceRepr + ValidAsZeroBits>(&self, len: usize) -> Result<Tensor<T>, DriverError> {\n");
    s.push_str("        Ok(Tensor { buf: self.stream.alloc_zeros::<T>(len)? })\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Downloads a tensor to host memory.\n");
    s.push_str("    pub fn download<T: DeviceRepr>(&self, tensor: &Tensor<T>) -> Result<Vec<T>, DriverError> {\n");
    s.push_str("        self.stream.clone_dtoh(&tensor.buf)\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Copies host data into an existing tensor.\n");
    s.push_str("    pub fn copy_from_slice<T: DeviceRepr>(&self, src: &[T], dst: &mut Tensor<T>) -> Result<(), DriverError> {\n");
    s.push_str("        assert!(dst.len() >= src.len(), \"destination tensor is smaller than source slice\");\n");
    s.push_str("        self.stream.memcpy_htod(src, &mut dst.buf)\n");
    s.push_str("    }\n\n");

    s.push_str("    /// Captures a fixed sequence of tensor operations into a CUDA graph.\n");
    s.push_str("    pub fn capture_graph<F>(&self, f: F) -> Result<CudaGraph, DriverError>\n");
    s.push_str("    where\n");
    s.push_str("        F: FnOnce(&Self) -> Result<(), DriverError>,\n");
    s.push_str("    {\n");
    s.push_str("        self.stream.begin_capture(sys::CUstreamCaptureMode::CU_STREAM_CAPTURE_MODE_GLOBAL)?;\n");
    s.push_str("        if let Err(err) = f(self) {\n");
    s.push_str("            let _ = self.stream.end_capture(sys::CUgraphInstantiate_flags::CUDA_GRAPH_INSTANTIATE_FLAG_AUTO_FREE_ON_LAUNCH);\n");
    s.push_str("            return Err(err);\n");
    s.push_str("        }\n");
    s.push_str("        let graph = self\n");
    s.push_str("            .stream\n");
    s.push_str("            .end_capture(sys::CUgraphInstantiate_flags::CUDA_GRAPH_INSTANTIATE_FLAG_AUTO_FREE_ON_LAUNCH)?\n");
    s.push_str("            .ok_or(DriverError(sys::CUresult::CUDA_ERROR_INVALID_VALUE))?;\n");
    s.push_str("        graph.upload()?;\n");
    s.push_str("        Ok(graph)\n");
    s.push_str("    }\n\n");

    for f in files {
        for k in &f.kernels {
            push_kernel_method(s, k);
        }
    }

    for f in native_files {
        for function in &f.functions {
            push_native_method(s, function);
        }
    }

    s.push_str("}\n\n");
}

fn push_native_method(s: &mut String, k: &crate::model::Kernel) {
    let n_param = k.params.iter().find(|p| !p.is_ptr && p.name == "n");
    let stream_param = k.params.iter().find(|p| !p.is_ptr && p.name == "stream");
    let first_ptr = k.params.iter().find(|p| p.is_ptr);
    let infer_n = n_param.is_some() && first_ptr.is_some();

    s.push_str(&format!(
        "    /// Calls the native CUDA `{}` launcher.\n",
        k.name
    ));
    s.push_str(&format!("    pub fn {}(&self", k.name));
    for p in &k.params {
        if (infer_n && !p.is_ptr && p.name == "n")
            || (stream_param.is_some() && !p.is_ptr && p.name == "stream")
        {
            continue;
        }
        if p.is_ptr {
            if p.is_const {
                s.push_str(&format!(", {}: &Tensor<{}>", p.name, p.base_ty));
            } else {
                s.push_str(&format!(", {}: &mut Tensor<{}>", p.name, p.base_ty));
            }
        } else {
            s.push_str(&format!(", {}: {}", p.name, p.rust_ty));
        }
    }
    s.push_str(") -> Result<(), DriverError> {\n");
    if infer_n {
        let first = first_ptr.unwrap();
        let n_ty = &n_param.unwrap().rust_ty;
        s.push_str(&format!("        let n_len = {}.len();\n", first.name));
        s.push_str(&format!(
            "        assert!({}.len() >= n_len, \"{} length is smaller than inferred n\");\n",
            first.name, first.name
        ));
        s.push_str(&format!("        let n = n_len as {};\n", n_ty));
    }
    for p in &k.params {
        if p.is_ptr {
            if p.is_const {
                s.push_str(&format!("        let ({}_ptr, _record_{}) = {}.as_cuda_slice().device_ptr(&self.stream);\n", p.name, p.name, p.name));
            } else {
                s.push_str(&format!("        let ({}_ptr, _record_{}) = {}.as_cuda_slice_mut().device_ptr_mut(&self.stream);\n", p.name, p.name, p.name));
            }
        }
    }
    s.push_str(&format!("        let status = unsafe {{ {}(", k.name));
    for (idx, p) in k.params.iter().enumerate() {
        if idx > 0 {
            s.push_str(", ");
        }
        if p.is_ptr {
            if p.is_const {
                s.push_str(&format!("{}_ptr as *const {}", p.name, p.base_ty));
            } else {
                s.push_str(&format!("{}_ptr as *mut {}", p.name, p.base_ty));
            }
        } else if p.name == "stream" {
            s.push_str("self.stream.cu_stream() as u64");
        } else {
            s.push_str(&p.name);
        }
    }
    s.push_str(") };\n");
    s.push_str("        if status == 0 { Ok(()) } else { Err(DriverError(sys::CUresult::CUDA_ERROR_UNKNOWN)) }\n");
    s.push_str("    }\n\n");
}

fn push_kernel_method(s: &mut String, k: &crate::model::Kernel) {
    let n_param = k.params.iter().find(|p| !p.is_ptr && p.name == "n");
    let first_ptr = k.params.iter().find(|p| p.is_ptr);
    let infer_n = n_param.is_some() && first_ptr.is_some();

    s.push_str(&format!("    /// Enqueues the `{}` CUDA kernel.\n", k.name));
    s.push_str(&format!("    pub fn {}(&self", k.name));
    for p in &k.params {
        if infer_n && !p.is_ptr && p.name == "n" {
            continue;
        }
        if p.is_ptr {
            if p.is_const {
                s.push_str(&format!(", {}: &Tensor<{}>", p.name, p.base_ty));
            } else {
                s.push_str(&format!(", {}: &mut Tensor<{}>", p.name, p.base_ty));
            }
        } else {
            s.push_str(&format!(", {}: {}", p.name, p.rust_ty));
        }
    }
    s.push_str(") -> Result<(), DriverError> {\n");

    if infer_n {
        let first = first_ptr.unwrap();
        let n_ty = &n_param.unwrap().rust_ty;
        s.push_str(&format!("        let n_len = {}.len();\n", first.name));
        s.push_str(&format!(
            "        assert!({}.len() >= n_len, \"{} length is smaller than inferred n\");\n",
            first.name, first.name
        ));
        s.push_str(&format!("        let n = n_len as {};\n", n_ty));
        s.push_str("        let cfg = LaunchConfig::for_num_elems(n_len as u32);\n");
    } else if n_param.is_some() {
        s.push_str("        let cfg = LaunchConfig::for_num_elems(n as u32);\n");
    } else {
        s.push_str("        let cfg = LaunchConfig::for_num_elems(1);\n");
    }

    s.push_str(&format!(
        "        let mut builder = self.stream.launch_builder(&self.func_{});\n",
        k.name
    ));
    for p in &k.params {
        if p.is_ptr {
            if p.is_const {
                s.push_str(&format!(
                    "        builder.arg({}.as_cuda_slice());\n",
                    p.name
                ));
            } else {
                s.push_str(&format!(
                    "        builder.arg({}.as_cuda_slice_mut());\n",
                    p.name
                ));
            }
        } else {
            s.push_str(&format!("        builder.arg(&{});\n", p.name));
        }
    }
    s.push_str("        unsafe { builder.launch(cfg) }.map(|_| ())\n");
    s.push_str("    }\n\n");
}

fn push_kernel_names(s: &mut String, files: &[KernelFile], native_files: &[NativeFile]) {
    s.push_str("/// Returns the CUDA kernel names discovered at build time.\n");
    s.push_str("pub fn kernel_names() -> &'static [&'static str] {\n    &[");
    let names: Vec<String> = files
        .iter()
        .flat_map(|f| f.kernels.iter().map(|k| format!("\"{}\"", k.name)))
        .chain(
            native_files
                .iter()
                .flat_map(|f| f.functions.iter().map(|k| format!("\"{}\"", k.name))),
        )
        .collect();
    s.push_str(&names.join(", "));
    s.push_str("]\n}\n\n");
}
